
// Code generated by core/assets/generator; DO NOT EDIT.

package assets

import "github.com/rabidaudio/tactics/sprite"

var Castle = sprite.OpenTileAsset("raw/HAS CreaturePack/HAS Creature Pack 1.2/Castle/CastleSpriteSheet.png", 16, 16)

func BishopAttack() sprite.Sprite {
	return Castle.SpriteFromRow(8, 12, 4)
}

func BishopDeath() sprite.Sprite {
	return Castle.SpriteFromRow(16, 12, 4)
}

func BishopHit() sprite.Sprite {
	return Castle.SpriteFromRow(12, 12, 4)
}

func BishopIdle() sprite.Sprite {
	return Castle.SpriteFromRow(0, 12, 4)
}

func BishopWalk() sprite.Sprite {
	return Castle.SpriteFromRow(4, 12, 4)
}

func Crossbow2Attack() sprite.Sprite {
	return Castle.SpriteFromRow(8, 10, 4)
}

func Crossbow2Death() sprite.Sprite {
	return Castle.SpriteFromRow(16, 10, 4)
}

func Crossbow2Hit() sprite.Sprite {
	return Castle.SpriteFromRow(12, 10, 4)
}

func Crossbow2Idle() sprite.Sprite {
	return Castle.SpriteFromRow(0, 10, 4)
}

func Crossbow2Walk() sprite.Sprite {
	return Castle.SpriteFromRow(4, 10, 4)
}

func CrossbowAttack() sprite.Sprite {
	return Castle.SpriteFromRow(8, 2, 4)
}

func CrossbowDeath() sprite.Sprite {
	return Castle.SpriteFromRow(16, 2, 4)
}

func CrossbowHit() sprite.Sprite {
	return Castle.SpriteFromRow(12, 2, 4)
}

func CrossbowIdle() sprite.Sprite {
	return Castle.SpriteFromRow(0, 2, 4)
}

func CrossbowWalk() sprite.Sprite {
	return Castle.SpriteFromRow(4, 2, 4)
}

func HalberdAttack() sprite.Sprite {
	return Castle.SpriteFromRow(8, 9, 4)
}

func HalberdDeath() sprite.Sprite {
	return Castle.SpriteFromRow(16, 9, 4)
}

func HalberdHit() sprite.Sprite {
	return Castle.SpriteFromRow(12, 9, 4)
}

func HalberdIdle() sprite.Sprite {
	return Castle.SpriteFromRow(0, 9, 4)
}

func HalberdWalk() sprite.Sprite {
	return Castle.SpriteFromRow(4, 9, 4)
}

func Knight2Attack() sprite.Sprite {
	return Castle.SpriteFromRow(8, 14, 4)
}

func Knight2Death() sprite.Sprite {
	return Castle.SpriteFromRow(16, 14, 4)
}

func Knight2Hit() sprite.Sprite {
	return Castle.SpriteFromRow(12, 14, 4)
}

func Knight2Idle() sprite.Sprite {
	return Castle.SpriteFromRow(0, 14, 4)
}

func Knight2Walk() sprite.Sprite {
	return Castle.SpriteFromRow(4, 14, 4)
}

func KnightAttack() sprite.Sprite {
	return Castle.SpriteFromRow(8, 7, 4)
}

func KnightDeath() sprite.Sprite {
	return Castle.SpriteFromRow(16, 7, 4)
}

func KnightHit() sprite.Sprite {
	return Castle.SpriteFromRow(12, 7, 4)
}

func KnightIdle() sprite.Sprite {
	return Castle.SpriteFromRow(0, 7, 4)
}

func KnightWalk() sprite.Sprite {
	return Castle.SpriteFromRow(4, 7, 4)
}

func MonkAttack() sprite.Sprite {
	return Castle.SpriteFromRow(8, 5, 4)
}

func MonkDeath() sprite.Sprite {
	return Castle.SpriteFromRow(16, 5, 4)
}

func MonkHit() sprite.Sprite {
	return Castle.SpriteFromRow(12, 5, 4)
}

func MonkIdle() sprite.Sprite {
	return Castle.SpriteFromRow(0, 5, 4)
}

func MonkWalk() sprite.Sprite {
	return Castle.SpriteFromRow(4, 5, 4)
}

func Rider2Attack() sprite.Sprite {
	return Castle.SpriteFromRow(8, 13, 4)
}

func Rider2Death() sprite.Sprite {
	return Castle.SpriteFromRow(16, 13, 4)
}

func Rider2Hit() sprite.Sprite {
	return Castle.SpriteFromRow(12, 13, 4)
}

func Rider2Idle() sprite.Sprite {
	return Castle.SpriteFromRow(0, 13, 4)
}

func Rider2Walk() sprite.Sprite {
	return Castle.SpriteFromRow(4, 13, 4)
}

func RiderAttack() sprite.Sprite {
	return Castle.SpriteFromRow(8, 6, 4)
}

func RiderDeath() sprite.Sprite {
	return Castle.SpriteFromRow(16, 6, 4)
}

func RiderHit() sprite.Sprite {
	return Castle.SpriteFromRow(12, 6, 4)
}

func RiderIdle() sprite.Sprite {
	return Castle.SpriteFromRow(0, 6, 4)
}

func RiderWalk() sprite.Sprite {
	return Castle.SpriteFromRow(4, 6, 4)
}

func SpearmanAttack() sprite.Sprite {
	return Castle.SpriteFromRow(8, 1, 4)
}

func SpearmanDeath() sprite.Sprite {
	return Castle.SpriteFromRow(16, 1, 4)
}

func SpearmanHit() sprite.Sprite {
	return Castle.SpriteFromRow(12, 1, 4)
}

func SpearmanIdle() sprite.Sprite {
	return Castle.SpriteFromRow(0, 1, 4)
}

func SpearmanWalk() sprite.Sprite {
	return Castle.SpriteFromRow(4, 1, 4)
}

func Swordsman2Attack() sprite.Sprite {
	return Castle.SpriteFromRow(8, 11, 4)
}

func Swordsman2Death() sprite.Sprite {
	return Castle.SpriteFromRow(16, 11, 4)
}

func Swordsman2Hit() sprite.Sprite {
	return Castle.SpriteFromRow(12, 11, 4)
}

func Swordsman2Idle() sprite.Sprite {
	return Castle.SpriteFromRow(0, 11, 4)
}

func Swordsman2Walk() sprite.Sprite {
	return Castle.SpriteFromRow(4, 11, 4)
}

func SwordsmanAttack() sprite.Sprite {
	return Castle.SpriteFromRow(8, 4, 4)
}

func SwordsmanDeath() sprite.Sprite {
	return Castle.SpriteFromRow(16, 4, 4)
}

func SwordsmanHit() sprite.Sprite {
	return Castle.SpriteFromRow(12, 4, 4)
}

func SwordsmanIdle() sprite.Sprite {
	return Castle.SpriteFromRow(0, 4, 4)
}

func SwordsmanWalk() sprite.Sprite {
	return Castle.SpriteFromRow(4, 4, 4)
}


var Rampart = sprite.OpenTileAsset("raw/HAS CreaturePack/HAS Creature Pack 1.2/Rampart/RampartSpriteSheet.png", 16, 16)

func AxemanAttack() sprite.Sprite {
	return Rampart.SpriteFromRow(8, 2, 4)
}

func AxemanDeath() sprite.Sprite {
	return Rampart.SpriteFromRow(16, 2, 4)
}

func AxemanHit() sprite.Sprite {
	return Rampart.SpriteFromRow(12, 2, 4)
}

func AxemanIdle() sprite.Sprite {
	return Rampart.SpriteFromRow(0, 2, 4)
}

func AxemanWalk() sprite.Sprite {
	return Rampart.SpriteFromRow(4, 2, 4)
}

func HammermanAttack() sprite.Sprite {
	return Rampart.SpriteFromRow(8, 10, 4)
}

func HammermanDeath() sprite.Sprite {
	return Rampart.SpriteFromRow(16, 10, 4)
}

func HammermanHit() sprite.Sprite {
	return Rampart.SpriteFromRow(12, 10, 4)
}

func HammermanIdle() sprite.Sprite {
	return Rampart.SpriteFromRow(0, 10, 4)
}

func HammermanWalk() sprite.Sprite {
	return Rampart.SpriteFromRow(4, 10, 4)
}

func Hunter2Attack() sprite.Sprite {
	return Rampart.SpriteFromRow(8, 12, 4)
}

func Hunter2Death() sprite.Sprite {
	return Rampart.SpriteFromRow(16, 12, 4)
}

func Hunter2Hit() sprite.Sprite {
	return Rampart.SpriteFromRow(12, 12, 4)
}

func Hunter2Idle() sprite.Sprite {
	return Rampart.SpriteFromRow(0, 12, 4)
}

func Hunter2Walk() sprite.Sprite {
	return Rampart.SpriteFromRow(4, 12, 4)
}

func HunterAttack() sprite.Sprite {
	return Rampart.SpriteFromRow(8, 4, 4)
}

func HunterDeath() sprite.Sprite {
	return Rampart.SpriteFromRow(16, 4, 4)
}

func HunterHit() sprite.Sprite {
	return Rampart.SpriteFromRow(12, 4, 4)
}

func HunterIdle() sprite.Sprite {
	return Rampart.SpriteFromRow(0, 4, 4)
}

func HunterWalk() sprite.Sprite {
	return Rampart.SpriteFromRow(4, 4, 4)
}


var Stronghold = sprite.OpenTileAsset("raw/HAS CreaturePack/HAS Creature Pack 1.2/Stronghold/StrongholdSpriteSheet.png", 16, 16)

func Brute2Attack() sprite.Sprite {
	return Stronghold.SpriteFromRow(8, 15, 4)
}

func Brute2Death() sprite.Sprite {
	return Stronghold.SpriteFromRow(16, 15, 4)
}

func Brute2Hit() sprite.Sprite {
	return Stronghold.SpriteFromRow(12, 15, 4)
}

func Brute2Idle() sprite.Sprite {
	return Stronghold.SpriteFromRow(0, 15, 4)
}

func Brute2Walk() sprite.Sprite {
	return Stronghold.SpriteFromRow(4, 15, 4)
}

func BruteAttack() sprite.Sprite {
	return Stronghold.SpriteFromRow(8, 7, 4)
}

func BruteDeath() sprite.Sprite {
	return Stronghold.SpriteFromRow(16, 7, 4)
}

func BruteHit() sprite.Sprite {
	return Stronghold.SpriteFromRow(12, 7, 4)
}

func BruteIdle() sprite.Sprite {
	return Stronghold.SpriteFromRow(0, 7, 4)
}

func BruteWalk() sprite.Sprite {
	return Stronghold.SpriteFromRow(4, 7, 4)
}

func GoblinRider2Attack() sprite.Sprite {
	return Stronghold.SpriteFromRow(8, 11, 4)
}

func GoblinRider2Death() sprite.Sprite {
	return Stronghold.SpriteFromRow(16, 11, 4)
}

func GoblinRider2Hit() sprite.Sprite {
	return Stronghold.SpriteFromRow(12, 11, 4)
}

func GoblinRider2Idle() sprite.Sprite {
	return Stronghold.SpriteFromRow(0, 11, 4)
}

func GoblinRider2Walk() sprite.Sprite {
	return Stronghold.SpriteFromRow(4, 11, 4)
}

func GoblinRiderAttack() sprite.Sprite {
	return Stronghold.SpriteFromRow(8, 3, 4)
}

func GoblinRiderDeath() sprite.Sprite {
	return Stronghold.SpriteFromRow(16, 3, 4)
}

func GoblinRiderHit() sprite.Sprite {
	return Stronghold.SpriteFromRow(12, 3, 4)
}

func GoblinRiderIdle() sprite.Sprite {
	return Stronghold.SpriteFromRow(0, 3, 4)
}

func GoblinRiderWalk() sprite.Sprite {
	return Stronghold.SpriteFromRow(4, 3, 4)
}

func MercenaryAttack() sprite.Sprite {
	return Stronghold.SpriteFromRow(8, 1, 4)
}

func MercenaryDeath() sprite.Sprite {
	return Stronghold.SpriteFromRow(16, 1, 4)
}

func MercenaryHit() sprite.Sprite {
	return Stronghold.SpriteFromRow(12, 1, 4)
}

func MercenaryIdle() sprite.Sprite {
	return Stronghold.SpriteFromRow(0, 1, 4)
}

func MercenaryWalk() sprite.Sprite {
	return Stronghold.SpriteFromRow(4, 1, 4)
}


var Tower = sprite.OpenTileAsset("raw/HAS CreaturePack/HAS Creature Pack 1.2/Tower/TowerSpriteSheet.png", 16, 16)

func Barbarian2Attack() sprite.Sprite {
	return Tower.SpriteFromRow(8, 9, 4)
}

func Barbarian2Death() sprite.Sprite {
	return Tower.SpriteFromRow(16, 9, 4)
}

func Barbarian2Hit() sprite.Sprite {
	return Tower.SpriteFromRow(12, 9, 4)
}

func Barbarian2Idle() sprite.Sprite {
	return Tower.SpriteFromRow(0, 9, 4)
}

func Barbarian2Sholder() sprite.Sprite {
	return Tower.SpriteFromRow(20, 9, 4).Reversed()
}

func Barbarian2Unsholder() sprite.Sprite {
	return Tower.SpriteFromRow(20, 9, 4)
}

func Barbarian2Walk() sprite.Sprite {
	return Tower.SpriteFromRow(4, 9, 4)
}

func BarbarianAttack() sprite.Sprite {
	return Tower.SpriteFromRow(8, 1, 4)
}

func BarbarianDeath() sprite.Sprite {
	return Tower.SpriteFromRow(16, 1, 4)
}

func BarbarianHit() sprite.Sprite {
	return Tower.SpriteFromRow(12, 1, 4)
}

func BarbarianIdle() sprite.Sprite {
	return Tower.SpriteFromRow(0, 1, 4)
}

func BarbarianSholder() sprite.Sprite {
	return Tower.SpriteFromRow(20, 1, 4).Reversed()
}

func BarbarianUnsholder() sprite.Sprite {
	return Tower.SpriteFromRow(20, 1, 4)
}

func BarbarianWalk() sprite.Sprite {
	return Tower.SpriteFromRow(4, 1, 4)
}

